Only check for Bundler Gemfile if env set
Calling File.exists? with a nil value results in an error:
    TypeError: can't convert nil into String
Check to see if the environment variable is set before looking for the
gemfile.